apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: devfile-sample-code-with-quarkus-likx
  namespace: karthik
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        appstudio.openshift.io/application: test-app-167111030
        appstudio.openshift.io/component: devfile-sample-code-with-quarkus-likx
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: devfile-sample-code-with-quarkus-likx-
      labels:
        appstudio.openshift.io/application: test-app-167111030
        appstudio.openshift.io/component: devfile-sample-code-with-quarkus-likx
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: karthik
    spec:
      params:
      - name: git-url
        value: https://github.com/dheerajodha/devfile-sample-code-with-quarkus
      - name: output-image
        value: quay.io/redhat-appstudio/user-workload:karthik-devfile-sample-code-with-quarkus-likx-$(tt.params.git-revision)
      - name: dockerfile
        value: https://raw.githubusercontent.com/dheerajodha/devfile-sample-code-with-quarkus/main/src/main/docker/Dockerfile.jvm.staged
      - name: path-context
        value: ./
      pipelineRef:
        bundle: quay.io/redhat-appstudio/hacbs-templates-bundle:latest
        name: docker-build
      podTemplate:
        imagePullSecrets:
        - name: redhat-appstudio-registry-pull-secret
      workspaces:
      - name: workspace
        volumeClaimTemplate:
          metadata:
            creationTimestamp: null
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
          status: {}
      - name: registry-auth
        secret:
          secretName: redhat-appstudio-registry-pull-secret
    status: {}
status: {}
